"use client";

import { ThemeProviderWrapper } from "@/contexts/ThemeContext";
import { ContextProvider } from "@/hooks/useStateContext";
import Layout from "@/components/layout";
import Authenticate from "@/components/Authenticate";
import { usePathname } from "next/navigation";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    const pathname = usePathname();
    const excludedPaths = ["/", "/login"];

    const shouldAuthenticate = !excludedPaths.includes(pathname);

    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <ThemeProviderWrapper>
                        {shouldAuthenticate ? (
                            <Authenticate>
                                <Layout>{children}</Layout>
                            </Authenticate>
                        ) : (
                            <Layout>{children}</Layout>
                        )}
                    </ThemeProviderWrapper>
                </ContextProvider>
            </body>
        </html>
    );
}
