import { ThemeProviderWrapper } from "@/contexts/ThemeContext";
import { ContextProvider } from "@/hooks/useStateContext";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
                </ContextProvider>
            </body>
        </html>
    );
}
