import { ThemeProviderWrapper } from "@/contexts/ThemeContext";
import { ContextProvider } from "@/hooks/useStateContext";
import Layout from "@/components/layout";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <ThemeProviderWrapper>
                        <Layout>{children}</Layout>
                    </ThemeProviderWrapper>
                </ContextProvider>
            </body>
        </html>
    );
}
